/*
 * generated by Xtext
 */
package org.xtext.example.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.documentation.IEObjectDocumentationProvider;
import org.eclipse.xtext.ui.editor.contentassist.IContentProposalProvider;
import org.eclipse.xtext.ui.editor.hover.IEObjectHover;
import org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider;

import hu.qgears.xtextdoc.editor.MyEObjectDocumentationProvider;
import hu.qgears.xtextdoc.editor.MyEObjectHover;
import hu.qgears.xtextdoc.editor.MyEObjectHoverProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MyDslUiModule extends org.xtext.example.mydsl.ui.AbstractMyDslUiModule {

	public MyDslUiModule(AbstractUIPlugin abstractUIPlugin) {
		super(abstractUIPlugin);
	}
	
	public Class<? extends IEObjectDocumentationProvider> bindIEObjectDocumentationProvider() {
		return MyEObjectDocumentationProvider.class;
	}

	@Override
	public Class<? extends IEObjectHover> bindIEObjectHover() {
		return MyEObjectHover.class;
	}

	@Override
	public Class<? extends IContentProposalProvider> bindIContentProposalProvider() {
		return MyProposalProvider.class;
	}
	
    public Class<? extends IEObjectHoverProvider> bindIEObjectHoverProvider() {
        return MyEObjectHoverProvider.class;
    }
    
}
