/*
 * generated by Xtext
 */
package org.xtext.example.mydsl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {
	
	@Inject
	private MyDslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser createParser() {
		org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser result = new org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getModelElementAccess().getAlternatives(), "rule__ModelElement__Alternatives");
					put(grammarAccess.getBookCategoryAccess().getAlternatives(), "rule__BookCategory__Alternatives");
					put(grammarAccess.getLibraryAccess().getGroup(), "rule__Library__Group__0");
					put(grammarAccess.getLibraryAccess().getGroup_3(), "rule__Library__Group_3__0");
					put(grammarAccess.getLibraryAccess().getGroup_3_0(), "rule__Library__Group_3_0__0");
					put(grammarAccess.getLibraryAccess().getGroup_3_1(), "rule__Library__Group_3_1__0");
					put(grammarAccess.getAuthorAccess().getGroup(), "rule__Author__Group__0");
					put(grammarAccess.getAuthorAccess().getGroup_3(), "rule__Author__Group_3__0");
					put(grammarAccess.getBookAccess().getGroup(), "rule__Book__Group__0");
					put(grammarAccess.getBookAccess().getGroup_3(), "rule__Book__Group_3__0");
					put(grammarAccess.getBookAccess().getGroup_3_0(), "rule__Book__Group_3_0__0");
					put(grammarAccess.getBookAccess().getGroup_3_1(), "rule__Book__Group_3_1__0");
					put(grammarAccess.getBookAccess().getGroup_3_2(), "rule__Book__Group_3_2__0");
					put(grammarAccess.getBookRatingAccess().getGroup(), "rule__BookRating__Group__0");
					put(grammarAccess.getBookRatingAccess().getGroup_3(), "rule__BookRating__Group_3__0");
					put(grammarAccess.getBookRatingAccess().getGroup_3_0(), "rule__BookRating__Group_3_0__0");
					put(grammarAccess.getBookRatingAccess().getGroup_3_1(), "rule__BookRating__Group_3_1__0");
					put(grammarAccess.getDomainModelAccess().getElementsAssignment(), "rule__DomainModel__ElementsAssignment");
					put(grammarAccess.getLibraryAccess().getNameAssignment_1(), "rule__Library__NameAssignment_1");
					put(grammarAccess.getLibraryAccess().getBooksAssignment_3_0_1(), "rule__Library__BooksAssignment_3_0_1");
					put(grammarAccess.getLibraryAccess().getAuthorsAssignment_3_1_1(), "rule__Library__AuthorsAssignment_3_1_1");
					put(grammarAccess.getAuthorAccess().getNameAssignment_1(), "rule__Author__NameAssignment_1");
					put(grammarAccess.getAuthorAccess().getBooksAssignment_3_1(), "rule__Author__BooksAssignment_3_1");
					put(grammarAccess.getBookAccess().getNameAssignment_1(), "rule__Book__NameAssignment_1");
					put(grammarAccess.getBookAccess().getPagesAssignment_3_0_1(), "rule__Book__PagesAssignment_3_0_1");
					put(grammarAccess.getBookAccess().getCategoryAssignment_3_1_1(), "rule__Book__CategoryAssignment_3_1_1");
					put(grammarAccess.getBookAccess().getAuthorsAssignment_3_2_1(), "rule__Book__AuthorsAssignment_3_2_1");
					put(grammarAccess.getBookRatingAccess().getNameAssignment_1(), "rule__BookRating__NameAssignment_1");
					put(grammarAccess.getBookRatingAccess().getBookAssignment_3_0_1(), "rule__BookRating__BookAssignment_3_0_1");
					put(grammarAccess.getBookRatingAccess().getRatingAssignment_3_1_1(), "rule__BookRating__RatingAssignment_3_1_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser typedParser = (org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser) parser;
			typedParser.entryRuleDomainModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
