/*
 * generated by Xtext
 */
package org.xtext.example.mydsl.validation;

import org.eclipse.xtext.validation.Check;
import org.xtext.example.mydsl.model.ModelElement;
import org.xtext.example.mydsl.model.ModelPackage;
import org.xtext.example.mydsl.version.VersionHandler;

import hu.qgears.documentation.DocumentationFieldUtils;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class MyDslJavaValidator extends AbstractMyDslValidator {

	@Check
	public void checkVersion(ModelElement modelElement) {
		try {
			int version = Integer.parseInt(DocumentationFieldUtils.getAnnotation(modelElement.eClass(), "version"));
			int limit = VersionHandler.getLimit();
			if (version > limit) {
				warning("Version number exceeds the limit: " + limit, ModelPackage.Literals.MODEL_ELEMENT__NAME);
			}
		} catch (NumberFormatException e) {

		}
	}

}
