/*
 * generated by Xtext
 */
package org.xtext.example.mydsl;

import org.eclipse.xtext.naming.IQualifiedNameProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyDslRuntimeModule extends org.xtext.example.mydsl.AbstractMyDslRuntimeModule {
	
	@Override
	public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return hu.qgears.xtextdoc.editor.MyDeclarativeQualifiedNameProvider.class;
	}
	 
}
